/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bus.gltf 
Author: VRC-IW (https://sketchfab.com/VRC-IW)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/japanese-bus-nishitetsu-bus-fukuoka-f8a7ccbc09d942ddb98499d092a3dc1e
Title: Japanese bus "Nishitetsu Bus" (Fukuoka)
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bus.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_nishitetsu_0.geometry} material={materials.nishitetsu} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.09} />
    </group>
  )
}

useGLTF.preload('/bus.gltf')
